steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest",
        "-f",
        "apps/a2a-agent/Dockerfile",
        "."
      ]
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE}:latest"
substitutions:
  _REGION: us-central1
  _REPO: ui-morn
  _IMAGE: a2a
